name: volunteer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  barcode_scanner: ^3.2.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  qrscan: 
  url_launcher: ^6.1.5
  walletconnect_dart: ^0.0.11
  walletconnect_secure_storage: ^1.0.0
  web3dart: ^2.3.5
  http: ^0.13.3
  flutter_local_notifications: 

dev_dependencies:
  cloud_firestore: ^3.4.4
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.5

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  google_fonts: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/abi.json
  