name: volunteer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.21.1
  flutter:
    sdk: flutter

dev_dependencies:
  cloud_firestore: ^3.4.4
  firebase_auth: ^3.4.2
  firebase_storage: ^10.3.5

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  google_fonts: ^3.0.1

flutter:

  uses-material-design: true
